module.exports = {
  SERVER_PORT: 3000,
  WEBPACK_DEV_SERVER_PORT: 3001,
  ETH_SERVER_PORT: 3002,
  AUTH_SERVER_PORT: 3003,
  DB_SERVER_PORT: 3004,
  BLOCKCHAIN_PORT: 8545,
  SECRET_OR_KEY: 'gustybanjo',
  SERVER_URL: 'http://localhost',
};
