module.exports = {
  ETH_SERVER_PORT: 3002,
  WEBPACK_DEV_SERVER_PORT: 3001,
  SERVER_PORT: 3000,
  SECRET_OR_KEY: 'gustybanjo',
  SERVER_URL: 'http://localhost',
  BLOCKCHAIN_PORT: 8545,
  AUTH_SERVER_PORT: 3003,
};
